
runtime: python37

env_variables:
  SECRET_KEY: 'IYr_2Ld5l6GZiHKUN0T2iA'
  PROJECT_ID: 'social-network-255302'
  DB_USER: 'root'
  DB_PASSWORD: 'bFMmgpdkb2ggm1uf'
  DB_NAME: 'network'
  DB_CONNECTION_NAME: 'social-network-255302:us-west2:socialnetwork'
